### ISSUE TITLE
API Dynamic Route (15 points)

### ISSUE THREAD

**Issue by elsafig** [elsafig/sqlalchemy-challenge-repo#7]
A start route that:

- [x] Accepts the start date as a parameter from the URL (2 points)

- [ ] Returns the min, max, and average temperatures calculated from the given start date to the end of the dataset (4 points)

A start/end route that:

- [x] Accepts the start and end dates as parameters from the URL (3 points)

- [ ] Returns the min, max, and average temperatures calculated from the given start date to the given end date (6 points)

**Comment by elsafig** [comment]
Couldn't get it. 
Traceback (most recent call last):
  File "C:\users\elsai\sqlalchemy-challenge-repo\SurfsUp\app.py", line 107, in <module>
    def start(start, end):
  File "C:\Python39\lib\site-packages\flask\scaffold.py", line 449, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
    return f(self, *args, **kwargs)
  File "C:\Python39\lib\site-packages\flask\app.py", line 1358, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: start
PS C:\users\elsai\sqlalchemy-challenge-repo\SurfsUp> python app.py

**Comment by elsafig** [comment]
There was another error becaues of line 50 where it was mad about my dynamic routes and my start date variable, regardless of me changing the variable name.
